version: "3.7"

services:
  web:
    container_name: "${PREFIX}web"
    build: "./${NAME_WEB}"
    restart: ${RESTART_NODE}
    networks:
      default:
      intNetwork:
        aliases:
          - ${NAME_WEB}
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - ${NAME_API}

  api:
    container_name: "${PREFIX}api"
    build: "./${NAME_API}"
    restart: ${RESTART_NODE}
    networks:
      intNetwork:
        aliases:
          - ${NAME_API}
      dbNetwork:
    depends_on:
      - ${NAME_DB}

  db:
    container_name: "${PREFIX}db"
    build: "./${NAME_DB}"
    restart: ${RESTART_DB}
    networks:
      dbNetwork:
        aliases:
          - ${NAME_DB}

networks:
  intNetwork:
  dbNetwork: